language: ruby
cache: bundler
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.10.6

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - marco.moura@gmail.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: 598a6fd29c27425f943a2b9f0a56161954fed36f4a7e51b7821b65eafa5018f3
