language: ruby
cache: bundler
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.10.6

script:
  - bundle exec rake
  - bundle exec rubocop

notifications:
  email:
    recipients:
      - marco.moura@gmail.com
    on_failure: change
    on_success: never
